version: '3.4'

services:
  accunetapi:
    ports:
      - "80"
  accucoreapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat

